name: iOS-ipa-build-react-native

on:
  workflow_dispatch: # Cho phép chạy thủ công

jobs:
  build-ios:
    name: 🎉 iOS Build (React Native)
    runs-on: macos-latest

    steps:
      # Bước 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Bước 2: Thiết lập Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Sử dụng phiên bản Node.js 18 (tương thích với React Native)

      # Bước 3: Lưu trữ cache cho node modules
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Bước 4: Cài đặt phụ thuộc
      - name: Install dependencies
        run: npm install

      # Bước 5: Cập nhật kho CocoaPods
      - name: Update CocoaPods repo
        run: pod repo update
        working-directory: ios

      # Bước 6: Cài đặt Pods
      - name: Install Pods
        run: pod install
        working-directory: ios

      # Bước 7: Build ứng dụng iOS (không ký mã)
      - name: Build iOS app
        run: |
          xcodebuild build \
            -workspace ios/MobileApp.xcworkspace \
            -scheme MobileApp \
            -configuration Release \
            -sdk iphoneos \
            -derivedDataPath ios/build \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO
        env:
          RCT_NO_LAUNCH_PACKAGER: 1 # Tắt Metro bundler

      # Bước 8: Tạo thư mục Payload
      - name: Create Payload directory
        run: mkdir Payload
        working-directory: ios/build/Build/Products/Release-iphoneos

      # Bước 9: Di chuyển tệp .app vào Payload
      - name: Move .app to Payload
        run: mv MobileApp.app Payload
        working-directory: ios/build/Build/Products/Release-iphoneos

      # Bước 10: Nén thành tệp IPA
      - name: Zip output
        run: zip -qq -r -9 ReactNativeIpaExport.ipa Payload
        working-directory: ios/build/Build/Products/Release-iphoneos

      # Bước 11: Tải IPA lên GitHub Releases
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ios/build/Build/Products/Release-iphoneos/ReactNativeIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is the first React Native iOS release for QTDmobile"